### PR TITLE
Add `Semaphore::add_permits()`

### PR DESCRIPTION
**Pull request by Jules-Bertholet**
Allows increasing the permit count of the semaphore after creation.

### CODE REVIEW

**Comment by Jules-Bertholet** [comment]
Test added

**Review by notgull — COMMENTED** [review]
Looks good to me, but I'd prefer to test the edge case.

Could you add a test where you have an `Acquire` future that tries to acquire a permit on a zero-permit `Semaphore`? It should return `Pending` (use `future::poll_once()` to test this). Then, once the `add_permits(1)` function is called, it should resolve to `Ready`. It should also test using another `Acquire` that should not be woken up by this call.

**Comment by Jules-Bertholet** [comment]
Test added

**Review by notgull — APPROVED** [review]
Thanks!

**Pull request merged**
