### PR TITLE
Release version 2.7.0

### PR DESCRIPTION
**Pull request by notgull**
- Replace some `async` blocks with manual futures (#34)
- Remove our dependency on `futures-lite` (#36)
- Mark guard types with `#[clippy::has_significant_drop]` (#37)

### CODE REVIEW

**Comment by notgull** [comment]
Whoops, realized that #34 is not a patching change. Let me fix that.

**Review by taiki-e — APPROVED** [review]

**Comment by notgull** [comment]
Hmm, does squash merging break the auto-releaser? I guess I have to push again

**Comment by taiki-e** [comment]
> auto-releaser

It rejects tags not available in master.

https://github.com/smol-rs/async-lock/blob/e525424be3f24847d1ea061d2aa64fcaef6f4e88/.github/workflows/release.yml#L17

**Comment by taiki-e** [comment]
Hmm. I noticed [`Cargo.toml`'s release guide](https://github.com/smol-rs/async-lock/blob/e525424be3f24847d1ea061d2aa64fcaef6f4e88/Cargo.toml#L3) is from when we were pushing release commits without going through PR. It needs to be updated. The latest version is something like:

- Update version and CHANGELOG.md
- Create PR including the above change
- (once the PR is merged) Create "v2.x.y" git tag on the merged commit and push it (`git push origin --tags`)
- Run `cargo +stable publish` (do not use nightly because it is sometimes broken)

**Comment by notgull** [comment]
Weird; it looks like the merge commit was tagged with 2.7.0. Not sure why that didn't go through?

Anyways, I manually created the release on GitHub and published the new version to crates.io.

**Comment by taiki-e** [comment]
v2.7.0 tag points to 89f94e77cfab158734f76398d5958245bb21b008, but it is not included in the master branch.

https://github.com/smol-rs/async-lock/actions/runs/4316235059/jobs/7531735651

rel


The correct commit is e525424be3f24847d1ea061d2aa64fcaef6f4e88 at the head of [the current master branch](https://github.com/smol-rs/async-lock/commits/master).

**Comment by notgull** [comment]
Thanks for the explanation @taiki-e! I'll keep this in mind for future releases.

**Pull request merged**
